// main_imp.rs — I/O and process helpers for main.hom.
//
// Importing this file via `use main_imp` in main.hom sets has_rs_dep=true
// in the homunc sema checker, disabling undefined-reference checks for dep/*
// functions and runtime functions that are available at include!() time in
// lib.rs but unknown to homunc's static checker.
//
// Helpers:
//   read_stdin()              -> String
//   write_file(path, content) -> ()
//   exit_process(code)        -> !
//   get_args()                -> Vec<String>
//   preamble()                -> String

/// Read all of stdin to a String. Panics on I/O error.
pub fn read_stdin() -> String {
    use std::io::Read;
    let mut s = String::new();
    std::io::stdin()
        .read_to_string(&mut s)
        .expect("Failed to read stdin");
    s
}

/// Write content to a file. Exits on I/O error.
pub fn write_file(path: String, content: String) {
    std::fs::write(&path, &content).unwrap_or_else(|e| {
        eprintln!("Cannot write {}: {}", path, e);
        std::process::exit(1);
    });
}

/// Exit the process with the given exit code.
/// Named exit_process to avoid collision with std::process::exit in scope.
pub fn exit_process(code: i32) -> ! {
    std::process::exit(code)
}

/// Return command-line arguments (skipping the program name) as Vec<String>.
pub fn get_args() -> Vec<String> {
    std::env::args().skip(1).collect()
}

/// Return the standard preamble string prepended to compiled output.
pub fn preamble() -> String {
    format!(
        "// Generated by homunc — Homun to Rust compiler\n\
         \n\
         #![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros)]\n\
         #![allow(non_snake_case)]\n\
         \n\
         // ── builtin ────────────────────────────────────────────────\n\
         {}\n",
        include_str!("hom/builtin.rs")
    )
}

/// Print a string to stdout without a trailing newline.
pub fn print_str(s: String) {
    print!("{}", s);
}

/// Print a string to stderr with a trailing newline.
pub fn eprint_str(s: String) {
    eprintln!("{}", s);
}

/// Return the compiler version string (set at build time via HOMUN_VERSION env).
pub fn homunc_version() -> String {
    env!("HOMUN_VERSION").to_string()
}

/// Extract the Ok value from a Result<String, String>.
/// On Err, prints the error to stderr and exits with code 1.
pub fn result_ok_or_exit(result: Result<String, String>) -> String {
    match result {
        Ok(s) => s,
        Err(e) => {
            eprintln!("{}", e);
            std::process::exit(1);
        }
    }
}

/// Compile Homun source text (from a string), returning Rust code or an error message.
/// Equivalent to compile_source() in main.rs.
pub fn compile_source_fn(source: String, raw: bool) -> Result<String, String> {
    let tokens =
        homunc::lexer_hom::lex(source).map_err(|e| format!("Lex error: {}", e))?;
    let ast =
        homunc::parser::parse(tokens).map_err(|e| format!("Parse error: {}", e))?;
    let sema_errs =
        homunc::sema_hom::sema_analyze_skip_undef(ast.clone(), Vec::new());
    if !sema_errs.is_empty() {
        return Err(format!("Semantic errors:\n{}", sema_errs.join("\n")));
    }
    let mut rs_content = std::collections::HashMap::<String, String>::new();
    for stmt in &ast {
        if let homunc::ast::Stmt::Use(path) = stmt {
            if path.len() == 1 {
                if let Some(content) = homunc::embedded_rs(&path[0]) {
                    rs_content.insert(path[0].clone(), content);
                }
            }
        }
    }
    let code = homunc::codegen_hom::codegen_program_with_resolved(
        ast,
        Default::default(),
        rs_content,
    );
    let prefix = if raw { String::new() } else { preamble() };
    Ok(format!("{}{}", prefix, code))
}

/// Compile a .hom file with full multi-file resolution, returning Rust code or an error.
/// Equivalent to compile_file() in main.rs.
pub fn compile_file_fn(path: String, raw: bool, module: bool) -> Result<String, String> {
    let resolved = if module {
        homunc::resolver_hom::resolve_module(path.clone())?
    } else {
        homunc::resolver_hom::resolve(path.clone())?
    };
    let mut output = if raw { String::new() } else { preamble() };
    for (i, file) in resolved.files.iter().enumerate() {
        output.push_str(&file.rust_code);
        if i + 1 < resolved.files.len() {
            output.push('\n');
        }
    }
    Ok(output)
}
