-- | homunc — Homun to Rust compiler
--
-- Usage:
--   homunc <input.hom>           # prints Rust to stdout
--   homunc <input.hom> -o <out>  # writes to file
--   homunc --help
--
-- Pipeline:
--   Source text
--     └─► Lexer   (Lexer.hs)   → [Token]
--     └─► Parser  (Parser.hs)  → Program (AST)
--     └─► Sema    (Sema.hs)    → Checked/annotated Program
--     └─► Codegen (Codegen.hs) → Rust source text
--
module Main where

import System.Environment (getArgs)
import System.Exit        (exitFailure, exitSuccess)
import System.IO          (hPutStrLn, stderr, writeFile)
import Data.List          (intercalate)

import Lexer    (lexHomun)
import Parser   (parseHomun)
import Sema     (analyzeProgram)
import Codegen  (codegenProgram)

-- ─────────────────────────────────────────
-- Main
-- ─────────────────────────────────────────

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> printHelp >> exitSuccess
    [src]      -> compileToStdout src
    [src, "-o", out] -> compileToFile src out
    _          -> do
      hPutStrLn stderr "Usage: homunc <input.hom> [-o output.rs]"
      exitFailure

printHelp :: IO ()
printHelp = mapM_ putStrLn
  [ "homunc — Homun to Rust compiler"
  , ""
  , "USAGE:"
  , "  homunc <input.hom>            Compile and print Rust to stdout"
  , "  homunc <input.hom> -o out.rs  Compile and write to file"
  , "  homunc --help                 Show this message"
  , ""
  , "PIPELINE:"
  , "  .hom source  →  Lexer  →  Parser  →  Sema  →  Codegen  →  .rs"
  , ""
  , "LANGUAGE FEATURES SUPPORTED:"
  , "  • Variable bindings      x := 10"
  , "  • Lambdas                fn := (a, b) -> { a + b }"
  , "  • Typed params           fn := (a: int, b: int) -> int { a + b }"
  , "  • Recursion              fib := (n) -> { if ... { fib(n-1) + fib(n-2) } }"
  , "  • Pipe operator          list | filter(f) | map(g)"
  , "  • Collections            @[], @{}, @()"
  , "  • Pattern match          match x { ... }"
  , "  • if/else, for, while"
  , "  • break => value         for ... do { break => val }"
  , "  • Structs & Enums"
  , "  • String interpolation   \"Hello ${name}\""
  , "  • RON load/save"
  ]

-- ─────────────────────────────────────────
-- Compile pipeline
-- ─────────────────────────────────────────

compile :: String -> String -> Either String String
compile filename source = do
  -- 1. Lex
  tokens <- mapErr "Lex error" $ lexHomun source

  -- 2. Parse
  ast    <- mapErr "Parse error" $ parseHomun tokens

  -- 3. Semantic analysis
  ast'   <- mapErr "Semantic errors" $ case analyzeProgram ast of
              Left errs -> Left (intercalate "\n" (map show errs))
              Right p   -> Right p

  -- 4. Code generation
  let rustSrc = preamble ++ "\n" ++ codegenProgram ast'

  return rustSrc

mapErr :: String -> Either String a -> Either String a
mapErr prefix (Left e)  = Left (prefix ++ ": " ++ e)
mapErr _ (Right a)       = Right a

compileToStdout :: FilePath -> IO ()
compileToStdout path = do
  src <- readFile path
  case compile path src of
    Left err  -> hPutStrLn stderr err >> exitFailure
    Right out -> putStr out

compileToFile :: FilePath -> FilePath -> IO ()
compileToFile src out = do
  source <- readFile src
  case compile src source of
    Left err   -> hPutStrLn stderr err >> exitFailure
    Right code -> do
      writeFile out code
      putStrLn $ "Compiled " ++ src ++ " → " ++ out

-- ─────────────────────────────────────────
-- Rust preamble: runtime support helpers
-- ─────────────────────────────────────────

preamble :: String
preamble = unlines
  [ "// Generated by homunc — Homun to Rust compiler"
  , ""
  , "#![allow(unused_variables, unused_mut, dead_code, unused_imports, unused_macros)]"
  , "#![allow(non_snake_case)]"
  , ""
  , "include!(\"std.rs\");"
  , ""
  ]
